import { DEMO_DEAL, DEMO_COMPARABLE_TRANSACTIONS } from '@/lib/demo-data'

function fmt(n: number) { return '$' + (n / 1000000).toFixed(1) + 'M' }

export default function ValuationPage() {
  const range = DEMO_DEAL.valuation_high - DEMO_DEAL.valuation_low
  const midPct = ((DEMO_DEAL.valuation_mid - DEMO_DEAL.valuation_low) / range) * 100

  return (
    <div style={{ padding: '28px 32px', fontFamily: "'Inter', system-ui, sans-serif", color: 'var(--kb-text)' }}>
      <div style={{ fontSize: '11px', color: 'var(--kb-text-muted)', letterSpacing: '0.08em', fontWeight: 510, textTransform: 'uppercase', marginBottom: '6px' }}>KB Valuation</div>
      <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: '28px', fontWeight: 600, margin: '0 0 5px', letterSpacing: '-0.3px' }}>Business Valuation Report</h1>
      <p style={{ fontSize: '14px', color: 'var(--kb-text-secondary)', margin: '0 0 28px' }}>Generated by the KB Deal Intelligence Engine using normalized EBITDA and industry-specific transaction multiples.</p>

      {/* Valuation Range */}
      <div style={{ background: 'linear-gradient(135deg, var(--kb-accent-dim), var(--kb-bg-panel))', border: '1px solid var(--kb-accent-border)', borderRadius: '8px', padding: '26px', marginBottom: '16px' }}>
        <div style={{ fontSize: '10px', color: 'var(--kb-accent)', fontWeight: 510, letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '18px' }}>Estimated Valuation Range</div>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: '14px' }}>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontFamily: "'Playfair Display', serif", fontSize: '26px', color: 'var(--kb-text-secondary)' }}>{fmt(DEMO_DEAL.valuation_low)}</div>
            <div style={{ fontSize: '11px', color: 'var(--kb-text-secondary)', marginTop: '3px' }}>Conservative</div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontFamily: "'Playfair Display', serif", fontSize: '38px', color: 'var(--kb-accent)', fontWeight: 600 }}>{fmt(DEMO_DEAL.valuation_mid)}</div>
            <div style={{ fontSize: '11px', color: 'var(--kb-accent)', fontWeight: 510, marginTop: '3px' }}>Fair Market Value</div>
          </div>
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontFamily: "'Playfair Display', serif", fontSize: '26px', color: 'var(--kb-green)', fontFamily: "'DM Mono', monospace", fontVariantNumeric: 'tabular-nums' }}>{fmt(DEMO_DEAL.valuation_high)}</div>
            <div style={{ fontSize: '11px', color: 'var(--kb-text-secondary)', marginTop: '3px' }}>Premium</div>
          </div>
        </div>
        <div style={{ position: 'relative', height: '8px', background: 'var(--kb-bg-raised)', borderRadius: '4px', margin: '6px 0' }}>
          <div style={{ position: 'absolute', left: 0, right: 0, height: '100%', background: 'linear-gradient(to right,rgba(201,168,76,0.4),#2ECC8B)', borderRadius: '4px' }} />
          <div style={{ position: 'absolute', top: '-4px', left: `${midPct}%`, transform: 'translateX(-50%)', width: '16px', height: '16px', borderRadius: '50%', background: 'var(--kb-accent)', border: '2px solid #0F2347', boxShadow: '0 0 0 3px rgba(201,168,76,0.3)' }} />
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: 'var(--kb-text-secondary)', marginTop: '8px' }}>
          <span>{DEMO_DEAL.ebitda_multiple_low}x EBITDA</span>
          <span>Asking: {fmt(DEMO_DEAL.asking_price)} ({(DEMO_DEAL.asking_price / DEMO_DEAL.normalized_ebitda).toFixed(1)}x)</span>
          <span>{DEMO_DEAL.ebitda_multiple_high}x EBITDA</span>
        </div>
      </div>

      {/* Multiple + Structure */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '16px' }}>
        <div style={{ background: 'var(--kb-bg-card)', border: '1px solid var(--kb-border)', borderRadius: '8px', padding: '22px' }}>
          <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)', fontWeight: 510, letterSpacing: '0.05em', textTransform: 'uppercase', marginBottom: '12px' }}>EBITDA Multiple Applied</div>
          <div style={{ fontFamily: "'Playfair Display', serif", fontSize: '30px', color: 'var(--kb-accent)', marginBottom: '5px' }}>{DEMO_DEAL.ebitda_multiple_low}x – {DEMO_DEAL.ebitda_multiple_high}x</div>
          <div style={{ fontSize: '13px', color: 'var(--kb-text-secondary)', marginBottom: '14px' }}>Industry: Home Services · DFW Market</div>
          <div style={{ padding: '12px', background: 'var(--kb-bg-raised)', borderRadius: '8px', fontSize: '12px', color: 'var(--kb-text-secondary)', lineHeight: 1.7 }}>
            Normalized EBITDA: <strong style={{ color: 'var(--kb-text)' }}>$1.05M</strong><br />
            Range: $1.05M × {DEMO_DEAL.ebitda_multiple_low}–{DEMO_DEAL.ebitda_multiple_high}x<br />
            Result: <strong style={{ color: 'var(--kb-green)' }}>$4.1M – $6.2M</strong>
          </div>
        </div>
        <div style={{ background: 'var(--kb-bg-card)', border: '1px solid var(--kb-border)', borderRadius: '8px', padding: '22px' }}>
          <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)', fontWeight: 510, letterSpacing: '0.05em', textTransform: 'uppercase', marginBottom: '12px' }}>Deal Structure Recommendation</div>
          <div style={{ marginBottom: '14px' }}>
            <div style={{ fontSize: '12px', color: 'var(--kb-accent)', fontWeight: 510, marginBottom: '5px' }}>Primary: SBA 7(a) Loan</div>
            <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)', lineHeight: 1.65 }}>Buyer brings $480K cash (10% down) · SBA bank loans $4.32M (90%) · Seller gets full price at close · 10-year term</div>
          </div>
          <div>
            <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)', fontWeight: 510, marginBottom: '5px' }}>Alternative: Blended Structure</div>
            <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)', lineHeight: 1.65 }}>75% SBA · 15% seller carries a note · 10% buyer cash down · Maximizes seller proceeds</div>
          </div>
        </div>
      </div>

      {/* AI Narrative */}
      <div style={{ background: 'linear-gradient(135deg, var(--kb-accent-dim), var(--kb-bg-panel))', border: '1px solid var(--kb-accent-border)', borderRadius: '8px', padding: '22px', marginBottom: '16px' }}>
        <div style={{ fontSize: '10px', color: 'var(--kb-accent)', fontWeight: 510, letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '12px' }}>Business Narrative</div>
        <p style={{ fontSize: '14px', color: 'var(--kb-text)', lineHeight: 1.85, margin: 0 }}>{DEMO_DEAL.ai_summary}</p>
      </div>

      {/* Risk + Value Drivers */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '14px', marginBottom: '16px' }}>
        <div style={{ background: 'var(--kb-bg-card)', border: '1px solid var(--kb-border)', borderRadius: '8px', padding: '22px' }}>
          <div style={{ fontSize: '14px', fontWeight: 510, marginBottom: '14px' }}>Risk Factors</div>
          {[
            { label: 'Owner Dependency', level: 'Medium', color: 'var(--kb-accent)', desc: 'Owner manages 3–4 key commercial accounts directly' },
            { label: 'Revenue Concentration', level: 'Low', color: 'var(--kb-green)', desc: 'No customer exceeds 8% of annual revenue' },
            { label: 'Market Competition', level: 'Low', color: 'var(--kb-green)', desc: '4.2* Google, dominant brand in DFW home services' },
          ].map(r => (
            <div key={r.label} style={{ marginBottom: '10px', padding: '12px', background: 'var(--kb-bg-raised)', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span style={{ fontSize: '13px' }}>{r.label}</span>
                <span style={{ fontSize: '11px', color: r.color, fontWeight: 510, padding: '2px 8px', background: `${r.color}18`, borderRadius: '4px' }}>{r.level}</span>
              </div>
              <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)' }}>{r.desc}</div>
            </div>
          ))}
        </div>
        <div style={{ background: 'var(--kb-bg-card)', border: '1px solid var(--kb-border)', borderRadius: '8px', padding: '22px' }}>
          <div style={{ fontSize: '14px', fontWeight: 510, marginBottom: '14px' }}>Value Drivers</div>
          {[
            { label: 'Recurring Contracts', stat: '42% of revenue', desc: 'Residential service agreements, predictable cash flow' },
            { label: 'Customer Database', stat: '2,400+ households', desc: 'Proprietary CRM with full service history' },
            { label: 'Tenured Tech Team', stat: 'Avg 7yr tenure', desc: '14 licensed technicians, runs without owner' },
          ].map(v => (
            <div key={v.label} style={{ marginBottom: '10px', padding: '12px', background: 'rgba(46,204,139,0.05)', border: '1px solid rgba(46,204,139,0.12)', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span style={{ fontSize: '13px' }}>{v.label}</span>
                <span style={{ fontSize: '11px', color: 'var(--kb-green)', fontWeight: 500 }}>{v.stat}</span>
              </div>
              <div style={{ fontSize: '12px', color: 'var(--kb-text-secondary)' }}>{v.desc}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Comparable Transactions */}
      <div style={{ background: 'var(--kb-bg-card)', border: '1px solid var(--kb-border)', borderRadius: '8px', padding: '22px' }}>
        <div style={{ fontSize: '14px', fontWeight: 510, marginBottom: '16px' }}>Comparable Transactions, Texas HVAC</div>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
          <thead>
            <tr>{['Business', 'Revenue', 'EBITDA', 'Multiple', 'Sale Price', 'Closed'].map(h => (
              <th key={h} style={{ textAlign: 'left', padding: '8px 12px', fontSize: '10px', fontWeight: 510, color: 'var(--kb-text-secondary)', letterSpacing: '0.08em', textTransform: 'uppercase', borderBottom: '1px solid rgba(201,168,76,0.18)' }}>{h}</th>
            ))}</tr>
          </thead>
          <tbody>
            {DEMO_COMPARABLE_TRANSACTIONS.map((t, i) => (
              <tr key={i} style={{ borderBottom: '1px solid var(--kb-border-subtle)' }}>
                <td style={{ padding: '12px' }}>{t.business}</td>
                <td style={{ padding: '12px', color: 'var(--kb-text-secondary)' }}>{t.revenue}</td>
                <td style={{ padding: '12px', color: 'var(--kb-text-secondary)' }}>{t.ebitda}</td>
                <td style={{ padding: '12px', color: 'var(--kb-accent)', fontWeight: 500 }}>{t.multiple}</td>
                <td style={{ padding: '12px', color: 'var(--kb-green)', fontWeight: 500 }}>{t.price}</td>
                <td style={{ padding: '12px', color: 'var(--kb-text-secondary)' }}>{t.close}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
